"""Failures a caller can act on. `code` is the wire code; the HTTP status is
the http layer's business, keyed on the class."""
from __future__ import annotations


class EggieError(Exception):
    def __init__(self, code: str, message: str, *, extra: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.extra = dict(extra or {})


class NotFound(EggieError): ...
class Conflict(EggieError): ...
class Invalid(EggieError): ...
class BadRequest(EggieError): ...
class Unauthorized(EggieError): ...
class Forbidden(EggieError): ...
class TooLarge(EggieError): ...
class DiskFull(EggieError): ...
class Upstream(EggieError): ...
class Unavailable(EggieError): ...
